### ISSUE TITLE
Docs do not build with latest sphinx 1.6.x

### ISSUE THREAD

**Issue by notatestuser** [CityOfZion/neon-js#111]
Self explanatory. Looks like `default_sidebars` was removed in sphinx-doc/sphinx#3590
```
$ npm run build:docs

> @cityofzion/neon-js@2.2.1 build:docs /home/ubuntu/dev/neon-js
> cd source && sphinx-versioning -g ../ -l ./conf.py build source ../docs

=> Reading config from ./conf.py...
Running Sphinx v1.6.5
WARNING: The config value `scv_whitelist_tags' has type `str', defaults to `tuple'.
loading pickled environment... not yet created

Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
```

Full trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
```

**Comment by snowypowers** [comment]
This is an issue with `sphinxcontrib-versioning`. We can move to 1.6x once they update. If they update... the repo looks dead, the fix is already in a PR but i doubt it will get pushed in.
